# Chapter 4 makefile.
#
# To build all the binaries for this chapter, simply run:
# $ make
#
# To remove the build products, including binaries, run:
# $ make clean
#  

eatyguys  = eatyguy6 eatyguy7 eatyguy8
obj_files = Pair.o cmodule.o
so_files  = Pair.$(so_ext) cmodule.$(so_ext)

include ../build_settings.make
