# Chapter 6 makefile.
#
# To build all the binaries for this chapter, simply run:
# $ make
#
# To remove the build products, including binaries, run:
# $ make clean
#  

eatyguys     = eatyguy10
interpreters = track_memory limit_memory limit_cpu
binaries     = library_subset
obj_files    = Pair.o interpreter.o

include ../build_settings.make
