# Chapter 5 makefile.
#
# To build all the binaries for this chapter, simply run:
# $ make
#
# To remove the build products, including binaries, run:
# $ make clean
#  

eatyguys  = eatyguy9
binaries  = lua_error lua_pcall
obj_files = Pair.o

include ../build_settings.make
